### PR TITLE
Michelle

### PR DESCRIPTION
**Pull request by MichelleNightward**
Pull request!

### CODE REVIEW

**Comment by nw0428** [comment]
Looking awesome!
It would be cool if the "Useful Links" div didn't look like a clickable link.
I would also love a little more styling on the index page.

Keep up the awesome work and make your commit messages a little more informative. =)

**Comment by MichelleNightward** [comment]
Will do, thanks David!

**Comment by nw0428** [comment]
LGTM

**Comment by MicahMartin** [comment]
lookgoodtome

**Pull request merged**
