### PR TITLE
Kai

### PR DESCRIPTION
**Pull request by MicahMartin**
Hey, Check out my pull request. Made a site, it's cool. check it out

### CODE REVIEW

**Comment by nw0428** [comment]
A few issues:
1. All I see is a blank, black page.
2. It appears that you deleted the index page which is supposed to link to all students pages.
3. You deleted my page!

**Comment by MicahMartin** [comment]
Hey, the only way i get github.io to host my site is by having the
directory really vanilla.. (one js folder, one css folder, one index.html)
could i put your a link to your page and link to all student pages in my
index.html?

**Comment by nw0428** [comment]
Well the idea behind this repo is that it would be shared between all students. What you do on your own personal site is your deal. Here though it would be better, I think, to have a shared index and then each student can have their own page. Feel free, however, to style the index as you desire.

Your page is working now! It looks awesome!

**Comment by MicahMartin** [comment]
Ok, I'll clone the master repo and rework this. Thanks for the direction!

**Comment by nw0428** [comment]
=)

**Comment by MicahMartin** [comment]
Hey, check things out now. I added my files in a 'kai' folder.

**Comment by nw0428** [comment]
Looking awesome! The only thing I would ask is that you include is a link to your page on the index page and maybe a link to your linkedIn or github on your page somewhere.

**Comment by MicahMartin** [comment]
Hey, hows this look?

**Comment by nw0428** [comment]
LGTM

LGTM

**Pull request merged**
